(hall-description
  (name "laco")
  (prefix "")
  (version "0.0.1")
  (author "Mu Lei known as NalaGinrut")
  (copyright (2020))
  (synopsis "Lambda Compiler")
  (description
    "Laco is a r7rs Scheme compiler for LambdaChip VM which is designed for functional programming on embedded system.")
  (home-page "https://lambdachip.com")
  (license gpl3+)
  (dependencies `(("guile" ,guile-3.0)))
  (files (libraries
           ((directory
              "laco"
              ((directory
                 "pass"
                 ((compiled-scheme-file "fold-branch")
                  (compiled-scheme-file "escape-analysis")
                  (compiled-scheme-file "primitive-conversion")
                  (compiled-scheme-file "useless-constant")
                  (compiled-scheme-file "dce")
                  (compiled-scheme-file "args-extend")
                  (compiled-scheme-file "useless-cont")
                  (compiled-scheme-file "delta-reduction")
                  (compiled-scheme-file "eta-cont")
                  (compiled-scheme-file "eta-func")
                  (compiled-scheme-file "fold-const")
                  (compiled-scheme-file "const-propagation")
                  (compiled-scheme-file "lambda-lifting")
                  (compiled-scheme-file "tco")
                  (compiled-scheme-file "func-inline")
                  (compiled-scheme-file "elre")
                  (compiled-scheme-file "normalize")
                  (compiled-scheme-file "closure-conversion")
                  (scheme-file "useless-cont")
                  (scheme-file "useless-constant")
                  (scheme-file "tco")
                  (scheme-file "primitive-conversion")
                  (scheme-file "normalize")
                  (scheme-file "lambda-lifting")
                  (scheme-file "func-inline")
                  (scheme-file "fold-const")
                  (scheme-file "fold-branch")
                  (scheme-file "eta-func")
                  (scheme-file "eta-cont")
                  (scheme-file "escape-analysis")
                  (scheme-file "elre")
                  (scheme-file "delta-reduction")
                  (scheme-file "dce")
                  (scheme-file "const-propagation")
                  (scheme-file "closure-conversion")
                  (scheme-file "args-extend")))
               (directory
                 "assembler"
                 ((compiled-scheme-file "encode")
                  (compiled-scheme-file "sasm")
                  (scheme-file "sasm")
                  (scheme-file "encode")))
               (directory "command" ())
               (directory
                 "lpass"
                 ((compiled-scheme-file "remove-unused-captures")
                  (compiled-scheme-file "fv-lifting")
                  (compiled-scheme-file "reduce-labels")
                  (compiled-scheme-file "closure-capture-fv")
                  (scheme-file "remove-unused-captures")
                  (scheme-file "reduce-labels")
                  (scheme-file "fv-lifting")
                  (scheme-file "closure-capture-fv")))
               (directory
                 "records"
                 ((compiled-scheme-file "syntactic")
                  (compiled-scheme-file "procedural")
                  (scheme-file "procedural")
                  (scheme-file "syntactic")))
               (scheme-file "records")
               (scheme-file "primitives")
               (scheme-file "utils")
               (scheme-file "types")
               (scheme-file "sasm")
               (scheme-file "pass")
               (scheme-file "parser")
               (scheme-file "object")
               (scheme-file "module")
               (scheme-file "lir")
               (scheme-file "env")
               (scheme-file "cps")
               (scheme-file "compile")
               (scheme-file "codegen")
               (scheme-file "assembler")
               (scheme-file "ast")))))
         (tests ((directory "tests" ())))
         (programs
           ((directory "scripts" ((in-file "laco")))))
         (documentation
           ((symlink "README" "README.org")
            (text-file "HACKING")
            (text-file "COPYING")
            (text-file "NEWS")
            (text-file "AUTHORS")
            (text-file "ChangeLog")
            (text-file "NEWS")
            (text-file "AUTHORS")
            (text-file "ChangeLog")
            (text-file "NEWS")
            (text-file "AUTHORS")
            (text-file "ChangeLog")
            (text-file "NEWS")
            (text-file "AUTHORS")
            (text-file "ChangeLog")
            (text-file "NEWS")
            (text-file "AUTHORS")
            (text-file "ChangeLog")
            (text-file "NEWS")
            (text-file "AUTHORS")
            (text-file "ChangeLog")
            (text-file "NEWS")
            (text-file "AUTHORS")
            (text-file "ChangeLog")
            (text-file "NEWS")
            (text-file "AUTHORS")
            (text-file "ChangeLog")
            (text-file "NEWS")
            (text-file "AUTHORS")
            (text-file "ChangeLog")
            (text-file "NEWS")
            (text-file "AUTHORS")
            (text-file "ChangeLog")
            (text-file "NEWS")
            (text-file "AUTHORS")
            (text-file "ChangeLog")
            (text-file "NEWS")
            (text-file "AUTHORS")
            (text-file "ChangeLog")
            (text-file "NEWS")
            (text-file "AUTHORS")
            (text-file "ChangeLog")
            (text-file "NEWS")
            (text-file "AUTHORS")
            (text-file "ChangeLog")
            (text-file "NEWS")
            (text-file "AUTHORS")
            (text-file "ChangeLog")
            (text-file "NEWS")
            (text-file "AUTHORS")
            (text-file "ChangeLog")
            (text-file "NEWS")
            (text-file "AUTHORS")
            (text-file "ChangeLog")
            (text-file "NEWS")
            (text-file "AUTHORS")
            (text-file "ChangeLog")
            (text-file "NEWS")
            (text-file "AUTHORS")
            (text-file "ChangeLog")
            (text-file "NEWS")
            (text-file "AUTHORS")
            (text-file "ChangeLog")
            (text-file "NEWS")
            (text-file "AUTHORS")
            (text-file "ChangeLog")
            (text-file "NEWS")
            (text-file "AUTHORS")
            (text-file "ChangeLog")
            (text-file "NEWS")
            (text-file "AUTHORS")
            (text-file "ChangeLog")
            (text-file "NEWS")
            (text-file "AUTHORS")
            (text-file "ChangeLog")
            (text-file "NEWS")
            (text-file "AUTHORS")
            (text-file "ChangeLog")
            (text-file "NEWS")
            (text-file "AUTHORS")
            (text-file "ChangeLog")
            (text-file "NEWS")
            (text-file "AUTHORS")
            (text-file "ChangeLog")
            (text-file "NEWS")
            (text-file "AUTHORS")
            (text-file "ChangeLog")
            (text-file "NEWS")
            (text-file "AUTHORS")
            (text-file "ChangeLog")
            (text-file "NEWS")
            (text-file "AUTHORS")
            (text-file "ChangeLog")
            (text-file "NEWS")
            (text-file "AUTHORS")
            (text-file "ChangeLog")
            (text-file "NEWS")
            (text-file "AUTHORS")
            (text-file "ChangeLog")
            (text-file "NEWS")
            (text-file "AUTHORS")
            (text-file "ChangeLog")))
         (infrastructure
           ((scheme-file "guix")
            (scheme-file "hall")
            (directory
              "build-aux"
              ((scheme-file "test-driver")
               (tex-file "texinfo")
               (text-file "missing")
               (text-file "mdate-sh")
               (text-file "install-sh")))
            (directory
              "build-aux"
              ((scheme-file "test-driver")
               (tex-file "texinfo")
               (text-file "missing")
               (text-file "mdate-sh")
               (text-file "install-sh")))
            (directory
              "build-aux"
              ((scheme-file "test-driver")
               (tex-file "texinfo")
               (text-file "missing")
               (text-file "mdate-sh")
               (text-file "install-sh")))
            (directory
              "build-aux"
              ((scheme-file "test-driver")
               (tex-file "texinfo")
               (text-file "missing")
               (text-file "mdate-sh")
               (text-file "install-sh")))
            (directory
              "build-aux"
              ((scheme-file "test-driver")
               (tex-file "texinfo")
               (text-file "missing")
               (text-file "mdate-sh")
               (text-file "install-sh")))
            (directory
              "build-aux"
              ((scheme-file "test-driver")
               (tex-file "texinfo")
               (text-file "missing")
               (text-file "mdate-sh")
               (text-file "install-sh")))
            (directory
              "build-aux"
              ((scheme-file "test-driver")
               (tex-file "texinfo")
               (text-file "missing")
               (text-file "mdate-sh")
               (text-file "install-sh")))
            (directory
              "build-aux"
              ((scheme-file "test-driver")
               (tex-file "texinfo")
               (text-file "missing")
               (text-file "mdate-sh")
               (text-file "install-sh")))
            (directory
              "build-aux"
              ((scheme-file "test-driver")
               (tex-file "texinfo")
               (text-file "missing")
               (text-file "mdate-sh")
               (text-file "install-sh")))
            (directory
              "build-aux"
              ((scheme-file "test-driver")
               (tex-file "texinfo")
               (text-file "missing")
               (text-file "mdate-sh")
               (text-file "install-sh")))
            (directory
              "build-aux"
              ((scheme-file "test-driver")
               (tex-file "texinfo")
               (text-file "missing")
               (text-file "mdate-sh")
               (text-file "install-sh")))
            (directory
              "build-aux"
              ((scheme-file "test-driver")
               (tex-file "texinfo")
               (text-file "missing")
               (text-file "mdate-sh")
               (text-file "install-sh")))
            (directory
              "build-aux"
              ((scheme-file "test-driver")
               (tex-file "texinfo")
               (text-file "missing")
               (text-file "mdate-sh")
               (text-file "install-sh")))
            (directory
              "build-aux"
              ((scheme-file "test-driver")
               (tex-file "texinfo")
               (text-file "missing")
               (text-file "mdate-sh")
               (text-file "install-sh")))
            (directory
              "build-aux"
              ((scheme-file "test-driver")
               (tex-file "texinfo")
               (text-file "missing")
               (text-file "mdate-sh")
               (text-file "install-sh")))
            (directory
              "build-aux"
              ((scheme-file "test-driver")
               (tex-file "texinfo")
               (text-file "missing")
               (text-file "mdate-sh")
               (text-file "install-sh")))
            (directory
              "build-aux"
              ((scheme-file "test-driver")
               (tex-file "texinfo")
               (text-file "missing")
               (text-file "mdate-sh")
               (text-file "install-sh")))
            (directory
              "build-aux"
              ((scheme-file "test-driver")
               (tex-file "texinfo")
               (text-file "missing")
               (text-file "mdate-sh")
               (text-file "install-sh")))
            (directory
              "build-aux"
              ((scheme-file "test-driver")
               (tex-file "texinfo")
               (text-file "missing")
               (text-file "mdate-sh")
               (text-file "install-sh")))
            (directory
              "build-aux"
              ((scheme-file "test-driver")
               (tex-file "texinfo")
               (text-file "missing")
               (text-file "mdate-sh")
               (text-file "install-sh")))
            (directory
              "build-aux"
              ((scheme-file "test-driver")
               (tex-file "texinfo")
               (text-file "missing")
               (text-file "mdate-sh")
               (text-file "install-sh")))
            (directory
              "build-aux"
              ((scheme-file "test-driver")
               (tex-file "texinfo")
               (text-file "missing")
               (text-file "mdate-sh")
               (text-file "install-sh")))
            (directory
              "build-aux"
              ((scheme-file "test-driver")
               (tex-file "texinfo")
               (text-file "missing")
               (text-file "mdate-sh")
               (text-file "install-sh")))
            (directory
              "build-aux"
              ((scheme-file "test-driver")
               (tex-file "texinfo")
               (text-file "missing")
               (text-file "mdate-sh")
               (text-file "install-sh")))
            (directory
              "build-aux"
              ((scheme-file "test-driver")
               (tex-file "texinfo")
               (text-file "missing")
               (text-file "mdate-sh")
               (text-file "install-sh")))
            (directory
              "build-aux"
              ((scheme-file "test-driver")
               (tex-file "texinfo")
               (text-file "missing")
               (text-file "mdate-sh")
               (text-file "install-sh")))
            (directory
              "build-aux"
              ((scheme-file "test-driver")
               (tex-file "texinfo")
               (text-file "missing")
               (text-file "mdate-sh")
               (text-file "install-sh")))
            (directory
              "build-aux"
              ((scheme-file "test-driver")
               (tex-file "texinfo")
               (text-file "missing")
               (text-file "mdate-sh")
               (text-file "install-sh")))
            (directory
              "build-aux"
              ((scheme-file "test-driver")
               (tex-file "texinfo")
               (text-file "missing")
               (text-file "mdate-sh")
               (text-file "install-sh")))
            (directory
              "build-aux"
              ((scheme-file "test-driver")
               (tex-file "texinfo")
               (text-file "missing")
               (text-file "mdate-sh")
               (text-file "install-sh")))
            (directory
              "build-aux"
              ((scheme-file "test-driver")
               (tex-file "texinfo")
               (text-file "missing")
               (text-file "mdate-sh")
               (text-file "install-sh")))
            (directory
              "build-aux"
              ((scheme-file "test-driver")
               (tex-file "texinfo")
               (text-file "missing")
               (text-file "mdate-sh")
               (text-file "install-sh")))
            (directory
              "build-aux"
              ((scheme-file "test-driver")
               (tex-file "texinfo")
               (text-file "missing")
               (text-file "mdate-sh")
               (text-file "install-sh")))))))
